### ISSUE TITLE
Not usable with Node.js version 24

### ISSUE THREAD

**Issue by mweidler** [sand4rt/ftp-deployer#29]
With using Node.js version 24, there is an issue
`TypeError: isDate is not a function`

As is seems that Node.js version 24 is now the default on github, the deployer is not usable any more.

Is it possible that you can also support version 24 of Node.js ?

Thanks and best regards,
Marc

**Comment by sand4rt** [comment]
AI created a fix. Do you want to test it?

**Comment by mweidler** [comment]
It's working without issues now, but there is still a warning:
**Node.js 20 is deprecated. The following actions target Node.js 20 but are being forced to run on Node.js 24: actions/checkout@v4.**

I assume you also have to fix the Node.js version in the file **action.yml** to:
runs:
  using: 'node**24**'
  main: 'dist/index.js

**Comment by sand4rt** [comment]
@mweidler Thanks! The warning should be gone now as well. Could you verify that everything is working correctly?

**Comment by mweidler** [comment]
Hi @sand4rt, yes, this issue is fixed and works fine with version 1.9.

But there is still this other warning regarding the Buffer() constructor:

```
(node:2113) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```
This might be fixed with your other pending PR. I've not tested that one.

Thanks for your work and best regards,
Marc

**Comment by sand4rt** [comment]
@mweidler great! thanks for testing. Would you mind testing the other PR as well? I don't use this plugin anymore, so it's difficult for me to test it myself.

**Comment by mweidler** [comment]
Hi @sand4rt, yes, I've tested the branch **copilot/fix-deprecation-warning-buffer** and everything works now perfect. No warnings.
Now your deployer is again in a perfect state.

Thanks for your work, I really appreciate it.

Best regards,
Marc

**Comment by sand4rt** [comment]
@mweidler awesome! i've released a new version
